# Generated by Django 5.2.3 on 2025-07-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/default.jpg', upload_to='event_images/'),
        ),
    ]
